### ISSUE TITLE
時々、Visual Compositorウインドウ操作中に、Visual Compositorのレイヤーの一つがDisplay8に反映されなくなります

### ISSUE THREAD

**Issue by MaronVtuber** [unity3d-jp/AnimeToolbox#11]
Visual Compositorウインドウ操作中に、Visual Compositorのレイヤーの一つがDisplay8に反映されなくなります。
主にノードの複製やレイヤーの生成に対してCtrl+ Zで操作を取り消した時などに発生します。

この現象は、Visual CompositorウインドウをClose Tabし、
再度メニューのWindow ⇒ Rendering ⇒ Visual Compositorから開きなおすことで改善します。

再度開いたとき、閉じる直前のレイヤー順と異なるレイヤー順で表示されることから、
閉じる直前の状態はウインドウに表示されている状態とVisual Compositorアセット内部のパラメータが同じではなかったと考えられます。

再現度が100%ではないためわかりづらいバグレポートになってしまいますが、
Ctrl + Zを使わない状態での作業が少し窮屈なため取り急ぎ報告させていただきました。

 - Unity Version: Unity2021.3.6f1
 - Render Pipeline: HDRPおよびBuiltInで確認

**Comment by sindharta-tanuwijaya** [comment]
@MaronVtuber 
ありがとうございます。確認いたします。

**Comment by sindharta-tanuwijaya** [comment]
@MaronVtuber こちらのバグについて、ほとんどのケースは [0.17.1-exp](https://github.com/unity3d-jp/AnimeToolbox/releases/tag/AnimeToolbox%400.17.1-exp) で修正されたかと思います。

もしまだ再現できてしまったら、報告をお願いいたします。
どうぞよろしくお願いいたします。

**Comment by sindharta-tanuwijaya** [comment]
特に問題がないようですので、このチケットをクローズします。
何かあれば、また再開して頂ければと思います。
