### ISSUE TITLE
Ctrl+Zを押すと、最小化していたnodeが勝手に開きます

### ISSUE THREAD

**Issue by project100man** [unity3d-jp/AnimeToolbox#15]
visual compositorで作業中、例えばあるノードの値を変更し、Ctrl＋Zで戻そうとすると、値は正常に戻るのですが、作業していない他の最小化していたノードが開きます

**Comment by sindharta-tanuwijaya** [comment]
このバグを確認しました。ご報告、ありがとうございます。

**Comment by sindharta-tanuwijaya** [comment]
このバグは [AnimeToolbox@0.18.1-exp](https://github.com/unity3d-jp/AnimeToolbox/releases/tag/AnimeToolbox%400.18.1-exp) で修正済です。
是非試してください。
