### ISSUE TITLE
Visual Compositorの名前が更新されない

### ISSUE THREAD

**Issue by project100man** [unity3d-jp/AnimeToolbox#16]
Visual Compositorの上部にeditting XXXXと名前が表示されますが、インスペクターやhierarcy上で名前を変更しても更新されません。またtimeline上のcontrol trackに貼ってあるVisual Copositorも変更されません

**Comment by sindharta-tanuwijaya** [comment]
ご報告、ありがとうございます。
確認のため、スクリーンショットなどを添付して頂けますでしょうか？

**Comment by project100man** [comment]
![スクリーンショット 2023-02-15 130616](https://user-images.githubusercontent.com/42921632/218929981-146896ba-cd29-4c01-b601-21ab753c9704.jpg)

**Comment by project100man** [comment]
GameObjectからインスペクターにてtestにリネームした後のスクリーンショットです

**Comment by sindharta-tanuwijaya** [comment]
この現象は [AnimeToolbox@0.18.1-exp](https://github.com/unity3d-jp/AnimeToolbox/releases/tag/AnimeToolbox%400.18.1-exp) で修正済です。
是非試してください。
