### ISSUE TITLE
unityを２バージョン続けてインストールするとテンプレートをコピーしてもHubに現れない

### ISSUE THREAD

**Issue by project100man** [unity3d-jp/AnimeToolbox#18]
unityを２バージョンインストールします

後からインストールしたunityに
https://note.com/nyaa_toraneko/n/nf8edfc3020bc
にあるようにテンプレートをコピーします

hubには現れません

再起動するとコピーしたテンプレートが削除されます。なおその後にコピーすれば現れます。

**Comment by sindharta-tanuwijaya** [comment]
ご報告、ありがとうございます。
お手数ですが、この不具合を再現するために、箇条書きなどで、もうちょっと具体的なステップを教えて頂けますでしょうか？

また、その際に
- 使っているOS
- インストールするUnityのバージョン
- 使っているUnity Hubのバージョン
- テンプレートのインストール先のフォルダ
- 可能であれば、スクリーンショットまたはビデオ
 
といった情報も頂けると幸いです。
よろしくお願いいたします。

**Comment by project100man** [comment]
unityhubをインストール　（3.4.1）

最初に出てくるインストールをスキップ

左メニューのインストールから2022.2.12f1をインストール

モジュールを加えるからVisualStudioをアンチェック　（アニメには必要ないので）
その他のオプションも全てアンチェック

ユーザーアカウント制御が表示されるのではい

インストール後
C:\Program Files\Unity\Hub\Editor\2022.3.12f1\Editor\Data\Resources\PackageManager\ProjectTemplates
に
com.unity.template.anime-0.18.1-exp.tgz
com.unity.template.anime.hdrp-0.18.1-exp.tgz
com.unity.template.anime.urp-0.18.1-exp.tgz
をコピーすると、新しいプロジェクトに
Anime(built-in)
Anime(HDRP)
Anime(Universal RP)
が現れる

引き続き2020.3.44f1をインストールする
モジュールを加えるはVisual Studioも含めて全部アンチェック

ユーザーアカウント制御が表示されずにインストールが完了　多分これが原因か

インストール後
C:\Program Files\Unity\Hub\Editor\2020.3.44f1\Editor\Data\Resources\PackageManager\ProjectTemplates
に 注1
com.unity.template.anime-0.18.1-exp.tgz
com.unity.template.anime.hdrp-0.18.1-exp.tgz
com.unity.template.anime.urp-0.18.1-exp.tgz
をコピーしても、新しいプロジェクトに
Anime(built-in)
Anime(HDRP)
Anime(Universal RP)
が現れない

パソコンを再起動すると現れるようになります

注1　再現しませんでしたが、元から入っている
com.unity.template.2d-5.0.2.tgz
com.unity.template.3d-6.0.1.tgz
com.unity.template.hd-10.8.0.tgz
がなく、新しいプロジェクトにも
２D　コア
３D　コア
が現れないと言う経験もあり。その場合、
com.unity.template.anime-0.18.1-exp.tgz
com.unity.template.anime.hdrp-0.18.1-exp.tgz
com.unity.template.anime.urp-0.18.1-exp.tgz
をコピーしても、新しいプロジェクトに
Anime(built-in)
Anime(HDRP)
Anime(Universal RP)
が現れない上に再起動すると上記のアニメテンプレート3ファイルが削除されてしまうため、ドツボに入ります。Twitterで困っている方を見かけましたので追記しました。

**Comment by Nobuyuki-Kobayashi** [comment]
追加の情報ありがとうございます。
ご報告を見た限りの印象ですが、あまり報告をいただいたことのない稀な事例のように思われます。
もう少し追加で情報をいただきたいと存じますので、以下の点に関してご確認をいただけますでしょうか？

- Unity Hubを同じシステムに複数インストールしているということはありませんか？
- Unity Hubがシステムにひとつしかインストールしていない場合、Unity Hubのインストールは正常に終了していますか？
- ご報告していただいた手順で、不具合は確実に発生しますか？
- もしお手元に他のPCがある場合、そちらでも同様の手順で不具合は発生しますか？
- 最後に、他の方の事例がTwitterであったとのことですが、どの方が報告をしていらっしゃるかリンクを教えていただけないでしょうか？

特に、「再起動した後で、テンプレートのファイル自体が消えてしまう」というのは、通常考えられない挙動です。
場合によっては、ご使用中のシステムやハードウェア自体の不具合もありえますので、追加の情報をいただければと存じます。

**Comment by Nobuyuki-Kobayashi** [comment]
> ユーザーアカウント制御が表示されずにインストールが完了　多分これが原因か

ご報告いただいた手順では、この2回目のインストールの際に「ユーザーアカウント制御が表示されない」というのは、正常な挙動ではないと思います。
おそらくこの挙動が発生した直後には、正常にUnityがインストール終了していないのかもしれません。
その場合には、Templateファイルを手操作でインストールしても、恐らくUnity Hubのほうが認識しない可能性はありえるかもしれません。

上のような状況が起こった場合の対処ですが、

・Anime Toolboxテンプレートを手操作でインストールする前に、一度Unity Hubを終了し、システムを再起動してから、再度、Unity Hubを立ち上げ、インストールしたUnityで正常に3Dコアなどの新規プロジェクトが作れることを確認してから、Anime Toolboxテンプレートを手操作でインストールする。

のが、よいかと思います。

もし上の手順で「正常に3Dコアなどの新規プロジェクトが作れなかった」場合には、Unityのインストール自体に失敗している可能性が高いので、該当するUnityを一度アンインストールしてから、インストールし直すことをお薦めいたします。

**Comment by project100man** [comment]
Unity Hubを同じシステムに複数インストールしているということはありませんか？
今日行った検証はUnity hubをアンインストールをしてからインストールを行いました。次回システムをクリーンアップした時にSDDをクリーンアップしてから再度検証を行って報告したいと思います。時間がかかるのでお待ちください。
Unity Hubがシステムにひとつしかインストールされていない場合、Unity Hubのインストールは正常に終了していますか？
正常かどうかの検査方法がわからないのでお答えできませんが、見た限りは正常に終了しています。

**Comment by Nobuyuki-Kobayashi** [comment]
本件ですが、「Unity HubからUnityをインストールする場合、ユーザーアカウント制御の確認がなされずに、Unityのインストールが完了することはない」とのことです。
従いまして、もし確実に再現性のある手順が発見された場合、恐らく不具合はUnity Hub側にあると思われます。
その場合、以下のリンク先にございます「Unity Hub からバグレポートを提出する方法」を参考に、Unity Hubのバグとしてご報告いただければと存じます。

以上、よろしくお願いします。

https://support.unity.com/hc/ja/articles/206336985-%E3%83%90%E3%82%B0%E3%83%AC%E3%83%9D%E3%83%BC%E3%83%88%E3%82%92%E6%8F%90%E5%87%BA%E3%81%99%E3%82%8B%E3%81%AB%E3%81%AF%E3%81%A9%E3%81%86%E3%81%97%E3%81%9F%E3%82%89%E3%81%84%E3%81%84%E3%81%A7%E3%81%99%E3%81%8B-

**Comment by project100man** [comment]
了解でさ
