### ISSUE TITLE
BallDance_AovExport.unity を開くとCompositorGraphの中にあるnormalやdepthが表示されない

### ISSUE THREAD

**Issue by romuhi** [unity3d-jp/AnimeToolbox#19]
Twitterで返事誠にありがとうございます。先程、Twitterでコメントされた通りTimeLineの再生ヘッドをスクラブしてみましたが
変化はありませんでした。

unity　hub 3.4.1
unity  2022.2..1f1

**Comment by romuhi** [comment]
unity　hub 3.4.1
unity  2022.2..1f1

**Comment by sindharta-tanuwijaya** [comment]
ご報告、ありがとうございます。
`BallDanceTemplate` プロジェクト内の `BallDance_AovExport.unity` のことですね。

こちらでは、[AnimeToolbox@0.18.1-exp](https://github.com/unity3d-jp/AnimeToolbox/releases/tag/AnimeToolbox%400.18.1-exp) を開いたところ、depth などは出ているようです。
![image](https://user-images.githubusercontent.com/71803280/222376031-0da84e2c-2bc0-41da-abd4-5ee04155da63.png)

そちらではプロジェクトがアップグレードされたようなので、お手数ですが、
下記のものもいただけますでしょうか？
* プロジェクト自体
* スクショ、または動画

よろしくお願いいたします。

**Comment by romuhi** [comment]
ありがとうございます。
お手数をおかけしました。
プロジェクトのバージョンを2020にしもう一度開き直しましたが、ちゃんと表示するようになりました。
![スクリーンショット 2023-03-02 180852](https://user-images.githubusercontent.com/126758607/222383169-84799513-42d0-41f8-8eb3-86d46e64f168.png)

**Comment by romuhi** [comment]
![image](https://user-images.githubusercontent.com/126758607/222383809-7af1466d-407c-4040-8624-a1cfc4be8c59.png)

**Comment by romuhi** [comment]
ありがとうございます。
少しごちゃごちゃになりましたので
一から入れ直しすと表示されました。
お手数をおかけしてしまい申し訳ありません。
![スクリーンショット 2023-03-02 180852](https://user-images.githubusercontent.com/126758607/222397243-62f4908e-8acf-43c6-a5d1-e6e5aa5b77b9.png)

**Comment by romuhi** [comment]
後、別件で質問なのですが、こちらのシーンを出力すると別々での画像として出力されましたが
全ての情報が入った画像を一枚で出力は可能なのでしょうか？
Photoshopで開くとこんなイメージです
![スクリーンショット 2023-03-02 192922](https://user-images.githubusercontent.com/126758607/222403252-b3c5c38a-eda2-400d-be07-93330c53a014.png)
![スクリーンショット 2023-03-02 193332](https://user-images.githubusercontent.com/126758607/222403861-70a78f04-4e37-4db1-b6d8-f1b1853f8f14.png)

**Comment by romuhi** [comment]
> > 全部の情報が入った画像を一枚で出力できるのでしょうか？
> 
> 今のところ、この機能は実装されていませんが、実はこの要望は別のユーザーからすでに頂いており、Unity内の他のチームとまだ一緒にどう解決できるかを議論しています。
> 
> こちらの問題に関して、特に問題があるのですが、閉じようと思いますが、いかがでしょうか？

そうだったんですね。
その情報を頂けただけで充分でした。
誠にありがとうございます。

**Comment by sindharta-tanuwijaya** [comment]
では、この issue を一旦クローズします。
今後もよろしくお願いします。
