### ISSUE TITLE
VisualCompositor Ver0.27.1でNodeのSizeをCustomにすると数値入力フォームが出現しません

### ISSUE THREAD

**Issue by kinamama** [unity3d-jp/AnimeToolbox#20]
VisualCompositor　Ver0.27.1から発生する不具合についてです。
2D Texture NodeやRenderingNodeなどのサイズを指定するNodeにおいて、
SizeからCustomを選んだ場合に数値を入力するフォームが出てこないです。
また描画もされなくなってしまいます。

VisualCompositorのバージョンを0.27.0に戻すと、入力できるようになります。
UnityEditorバージョンは2020.3.45fと2021.3.19f1でこの現象を確認しました。

![image](https://user-images.githubusercontent.com/67040728/222438199-2db1ae1f-b324-4bd3-ba49-b9da3422217b.png)

**Comment by sindharta-tanuwijaya** [comment]
バグを確認しました。ご報告、ありがとうございます。
こちらに関してはすぐに修正したいと考えています。少々お待ちください。

`VisualCompositor＠0.27.0`には色々なバグがまだ残っており、当面はなるべく別のバージョンを使って頂ければと思います。

**Comment by sindharta-tanuwijaya** [comment]
`VisualCompositor＠0.27.2` をリリースしました。
このバージョンでこのバグが治ったかと思います。
よろしくお願いします。

**Comment by kinamama** [comment]
修正確認できました、ありがとうございます！
