### ISSUE TITLE
VisualCompositorで粗く表示されているShadowをスムーズにすることは可能でしょうか？

### ISSUE THREAD

**Issue by romuhi** [unity3d-jp/AnimeToolbox#22]

**Comment by sindharta-tanuwijaya** [comment]
プロジェクトや画像などを見ないとあまり答えられませんが、これは GameView での Shadow の結果と比べて、VisualCompositor で描画された Shadow の結果が粗いということでしょうか？

**Comment by romuhi** [comment]
そうですね。
事情により、画像は出せませんがアニメ風なシャドウの描画の線がギザギザに表示されましたの
これを真っ直ぐに描画できるVisualCompositorで修正出来ないかと思いました

**Comment by sindharta-tanuwijaya** [comment]
GameView と VisualCompositor の違いのスクショを見ないと、少々判断はできかねます。
この報告を再現できるサンプルプロジェクトなどを作って頂くことは可能でしょうか？

**Comment by sindharta-tanuwijaya** [comment]
返事がないため、一旦クローズしてしまいます。
この件についてまた確認したいことがありましたら、この issue を再開して頂ければと思います。
