### ISSUE TITLE
VIsual CompositorのRenderingNodeのSizeの変更ができない

### ISSUE THREAD

**Issue by rarusun** [unity3d-jp/AnimeToolbox#23]
**Describe the bug**
[今日からはじめるAnime Toolbox 第3回『Anime Toolboxを使ってみよう！～3Dモデルを2D素材と簡単合成してみよう』](https://note.com/nyaa_toraneko/n/n2b0c0f4ecf18)
の「最後にVisual Compositorを使えるようにしましょう」まで進めたのですが、VIsual CompositorのRenderingNodeのSizeを変更する場所がありません。

またこのまま進めていった結果、「2D画像を背景として表示してみよう」ではユニティちゃんのSizeが1621x2048ではなく1920x1080になります。
「ユニティちゃんの表示を良い感じに調整しよう」で、TransformerNodeのScale ParameterをいじればDisplay上ではそれっぽくはなります。

こちらはバグなのか、自分のミスかはわからないですがサイズの変更方法を教えていただきたいです。

**To Reproduce**
[今日からはじめるAnime Toolbox 第3回『Anime Toolboxを使ってみよう！～3Dモデルを2D素材と簡単合成してみよう』](https://note.com/nyaa_toraneko/n/n2b0c0f4ecf18)
にそって進める

**Screenshots**
![not_find_custom_size](https://user-images.githubusercontent.com/27908496/223534571-2c33215c-94a7-4149-8e8b-72c520a3af3d.png)

![not_find_custom_size_2](https://user-images.githubusercontent.com/27908496/223534657-cada00aa-e916-44e3-b6c0-7c92f8433bf1.png)

![not_find_custom_size_on_unity_ chan](https://user-images.githubusercontent.com/27908496/223534690-43c39ece-3a10-4481-b3c0-b0803bd33f59.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home

**Unity (please complete the following information):**
 - Unity Version: 2020.3.44f1
 - Render Pipeline: URP

**Comment by rarusun** [comment]
https://github.com/unity3d-jp/AnimeToolbox/issues/20
のIssueと同じ問題だったので解決しました、おさわがせしました、すみません。

**Comment by sindharta-tanuwijaya** [comment]
解決できて、よかったです！
