### ISSUE TITLE
VisualCompositorでモデルを非表示にし、outlineだけを表示させることは可能でしょうか？

### ISSUE THREAD

**Issue by romuhi** [unity3d-jp/AnimeToolbox#24]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Unity (please complete the following information):**
 - Unity Version[e.g. Unity 2020]
 - Render Pipeline: [e.g. URP]

**Additional context**

**Comment by romuhi** [comment]
ちなみに、DrawnEdgesNodeを使ってみましたが、こちらはshadowなどのEdgesにも反応してしまいましたのでダメでした

**Comment by sindharta-tanuwijaya** [comment]
なにがダメで、何が良いかを確認できるスクショなどを添付して頂かないと、こちらとしては想像しかでくなくなってしまい、要望に合うものが実装できなくなります。
なので、是非スクショなどを添付してください。

ちなみに、DrawnEdgesNode は Outline だけを表示しています。下記は[ドキュメント](https://docs.unity3d.com/ja/Packages/com.unity.visual-compositor@0.27/manual/nodes.html#drawn-edges
)から撮った画像です。

![image](https://user-images.githubusercontent.com/71803280/224886689-040c0e89-abac-4ad4-9d6f-53cfbd0f8f17.png)

Shadow の影響が出てほしくないのであれば、RenderNode で Shadow が出ないように調整してみてください。

**Comment by sindharta-tanuwijaya** [comment]
返事がないため、一旦クローズしてしまいます。
この件についてまた確認したいことがありましたら、この issue を再開して頂ければと思います。
