### ISSUE TITLE
edge detectionのアルゴリズムについて

### ISSUE THREAD

**Issue by project100man** [unity3d-jp/AnimeToolbox#26]
背面法なのかsobelなのかマニュアルに明記していただけると嬉しいです
後、Canny edge detectionをサポートしていただけると嬉しいです、アニメに有効な均一な線がでやすいので

**Comment by sindharta-tanuwijaya** [comment]
フィードバックを頂き、誠にありがとうございます。
今回は `DrawnEdgesNode` に関する問い合わせでよろしいでしょうか？

であれば、`DrawnEdgesNode` は独自の手法で実装しています。
Canny Edge Detection については今後の開発に検討させていただきます。

**Comment by project100man** [comment]
独自なんですね、お返事ありがとうございます

**Comment by sindharta-tanuwijaya** [comment]
因みに、今週リリースした `com.unity.visual-compositor@0.28.1-preview` に [OutlineNode](https://docs.unity3d.com/ja/Packages/com.unity.visual-compositor@0.28/manual/nodes.html#outline) を追加しました。

用途は DrawnEdgesNode と同じですが、手法がかなり違うので、別のノードとして追加する形になりました。
是非試していただければと思います。

**Comment by project100man** [comment]
╰(*°▽°*)╯
