### ISSUE TITLE
In Unity 2023, VisualCompositor seems to be unable to integrate with Timeline

### ISSUE THREAD

**Issue by ShiinaRinne** [unity3d-jp/AnimeToolbox#32]
**Describe the bug**
Can't drag the internal object from the node to Timeline

- 2023
https://github.com/unity3d-jp/AnimeToolbox/assets/45081750/76b555ca-2a29-48ad-99ba-12255685e23f

- 2022
https://github.com/unity3d-jp/AnimeToolbox/assets/45081750/aefccb4b-8fb5-4b3f-addf-b552c7cec980

**To Reproduce**
1. Create a empty project add install VisualCompositor `com.unity.visual-compositor`
2. Create a VisualCompositor Graph and open it
3. Create any node that can be exposed, then click `Exposed  As Component`
4. Drag the internal object from the node

**Unity (please complete the following information):**
 - Unity 2023.2.3f1

Source Project
[VirtualCompositor-2023.zip](https://github.com/unity3d-jp/AnimeToolbox/files/13671252/VirtualCompositor-2023.zip)

**Comment by sindharta-tanuwijaya** [comment]
Thank you for your feedback. I have confirmed your issue using Unity 2023.2.3f1, and I'll get back to you

**Comment by sindharta-tanuwijaya** [comment]
We have just released `com.unity.visual-compositor@0.30.4-preview` which addressed this issue.
Please let us know how it goes for you, and feel free to reopen this issue if it persists in your project.

**Comment by ShiinaRinne** [comment]
Thank you for your fix. It is now working properly on Unity2023!


But I found a new problem: when I click the record button and paste a value into the Node, it will not create a new keyframe to apply this value.

https://github.com/unity3d-jp/AnimeToolbox/assets/45081750/22e9f8ec-45b7-4796-b248-4b8972bee6ba

I suspect that this issue may be caused by the use `delayCall` to record keyframes in `Editor/Scripts/NodeEditors/CompostorNodeEditor.cs`
Or when pasting values, it will not be immediately updated to the Node.

I'm sorry I don't have experience and I'm not sure if it's caused by this, nor do I know how to fix it
![image](https://github.com/unity3d-jp/AnimeToolbox/assets/45081750/209ff75e-c2f3-4e0b-9477-c551d9110437)


Do I need to open a new issue?

**Comment by sindharta-tanuwijaya** [comment]
Thank you for reporting this.

> Do I need to open a new issue?

Yes please, for record purposes.
