### ISSUE TITLE
VisualCompositor Node does not record pasted values during recording

### ISSUE THREAD

**Issue by ShiinaRinne** [unity3d-jp/AnimeToolbox#33]
**Describe the bug**
When enable the node’s recording function, if a value is directly pasted into the node’s field, this pasted value will not be properly recorded into the clip. 
When directly modified, this issue will not be triggered

**To Reproduce**
1. Create a new VisualCompositor Grah
2. Create a Node and click "Expose As Component", then drag it to Timeline
3. Click record button
4. Paste a value into any field, and observe the curves in the Timeline, please see attachment
5. See error

**Expected behavior**
Timeline should be the same as when directly modified, immediately record this value

**Screenshots**
https://github.com/unity3d-jp/AnimeToolbox/assets/45081750/22e9f8ec-45b7-4796-b248-4b8972bee6ba

**Unity (please complete the following information):**
 - Unity Version 2023.2.3f1

**Additional context**
I believe this error is caused by this code at `100~101` line in `Editor/Scripts/NodeEditors/CompositorNodeEditor.cs`. 
When a value is directly pasted to trigger this callback, `Event.current` is null, and it will return directly without recording the value. 
Although deleting this part directly can achieve the expected result, but it may cause unexpected errors. 

I’m sorry I don’t have experience and I’m not sure how to best fix this problem.
![image](https://github.com/unity3d-jp/AnimeToolbox/assets/45081750/ff3a92fb-d22b-4e0a-a2a7-cabb54fcd51c)

**Comment by sindharta-tanuwijaya** [comment]
I watched your video, and I am wondering if you are trying to paste values outside the time clip ?

**Comment by sindharta-tanuwijaya** [comment]
Actually, I managed to repro your issue in 2023.2.3f1 as you wrote.
Thank you for reporting this, and I'll post an update when I have a fix.

**Comment by sindharta-tanuwijaya** [comment]
Hello, please try `VisualCompositor@0.30.5-preview` and see if it resolves this issue for you.

**Comment by ShiinaRinne** [comment]
Yes, thank you very much for fixing it~
