### ISSUE TITLE
KeyNotFoundException for PatchPanelNode on Project Reopen

### ISSUE THREAD

**Issue by ShiinaRinne** [unity3d-jp/AnimeToolbox#34]
**Describe the bug**
When closing the project and reopening it, `PatchPanelNode` will cause an error

**To Reproduce**
1. Create a Graph file and add a `PatchPanelNode`
2. Save the project and close it.
3. Reopen the project. At this point, the `KeyNotFoundException` error is immediately triggered.

**Expected behavior**
The `PatchPanelNode` should maintain its state across project sessions without causing a `KeyNotFoundException`.

**Screenshots**
![45bce81e55d600ea5fc47c174c15aa5f](https://github.com/unity3d-jp/AnimeToolbox/assets/45081750/0f78d484-a888-49e1-8754-f4d16c044bae)

**Unity (please complete the following information):**
 - Unity Version: 2023.2.4
 - Render Pipeline: BRP/URP

**Additional context**
Deleting and recreating the `PatchPanelNode` resolves the issue temporarily, but the error reoccurs when the project is reopened.
It appears the cause of the problem is that PatchPanelNode's initialization method `InitInternalV` is only called upon creation. 
so, when the project is reopened, the node lacks proper initialization, leading to the aforementioned error.
![image](https://github.com/unity3d-jp/AnimeToolbox/assets/45081750/ce67ae91-95da-4663-826c-a2b5895f0d12)

**Source Project**
[VisualCompositor-PatchPanelBug.zip](https://github.com/unity3d-jp/AnimeToolbox/files/14427733/VisualCompositor-PatchPanelBug.zip)

**Comment by sindharta-tanuwijaya** [comment]
Thank you for the report. We'll look into it.

**Comment by sindharta-tanuwijaya** [comment]
This has been fixed in `com.unity.visual-compositor@0.30.6-preview`
Would you please kindly check ?

**Comment by ShiinaRinne** [comment]
Thank you for your assistance in resolving this issue, it has now been fixed!
